spring:
  profiles:
    active: dev
  datasource: # 数据源的相关配置
    type: com.zaxxer.hikari.HikariDataSource          # 数据源类型：HikariCP
    driver-class-name: com.mysql.cj.jdbc.Driver          # mysql驱动
    url: jdbc:mysql://localhost:3306/work?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: q1441139874Q